/*
  * $.SpMsgBox - Customized Jquery for model Alerts in Web Applications
  *
- * Copyright (c) 2014 
- * Dual licensed under the MIT and GPL licenses.
+ * Copyright 2014, 
+ * Dual licensed under the MIT or GPL Version 2 licenses.
+ * http://jquery.org/license
  *
  */
$.SPMsgBox={msg_ctr:0,lastPos:undefined,settings:{inEffect:{opacity:"show"},inEffectDuration:600,stayTime:3000,Msg:"",autoHide:false,type:"notice",position:"top-right",closeText:"",close:null,progressBar:false,bkColor1:"#062338",bkColor2:"#20282e",pBarColor:"#f5db0f",borderColor:"",textColor:null,title:"",titleColor:"#fff",hideCloseIcon:false,iconUrl:null},JMBContainer:function(e){function l(){var e=(f.hidetm-(new Date).getTime())/f.maxHtm*100;o.width(e+"%")}function c(e){if($(":focus",r).length&&!e){return}clearTimeout(f.intId)}var t,n,r,i,s,o,u,a;var f={intId:null,hidetm:null,maxHtm:null};if($.SPMsgBox.lastPos!="jmb-position-"+e.position){$("#Container").remove()}if(!$(".jmb-container").length){t=$('<div id="Container"></div>').addClass("jmb-container").addClass("jmb-position-"+e.position).appendTo("body")}else{t=$(".jmb-container")}$.SPMsgBox.lastPos="jmb-position-"+e.position;n=$('<div id="jpopup'+$.SPMsgBox.msg_ctr+'"></div>');o=$("<div></div>");a=$("<div><h1>"+e.title+"</h1></div>").addClass("jmb-title");u="linear-gradient(to bottom, "+e.bkColor1+" 0%,"+e.bkColor2+" 100%)";r=$("<div></div>").hide().addClass("jmb-item jmb-type-"+e.type).appendTo(t).html($("<p>").append(e.Msg)).animate(e.inEffect,e.inEffectDuration).wrap(n);if(!e.hideCloseIcon){i=$("<div></div>").addClass("jmb-item-close").prependTo(r).click(function(){$.SPMsgBox.remove(r,e)})}else{i=$("<div></div>").addClass("jmb-item-closetxt").prependTo(r).html(e.closeText).click(function(){$.SPMsgBox.remove(r,e)})}s=$("<div></div>").addClass("jmb-item-image").addClass("jmb-item-image-"+e.type).prependTo(r);if(e.type==null||e.type==""){$(".jmb-item p").css({margin:"6px 0px 0px 0px"})}if(e.iconUrl!=null&&e.iconUrl!=""){$(".jmb-item-image").css({background:"url("+e.iconUrl+")"})}$(".jmb-item").css({background:u});$(".jmb-type-"+e.type).css({"border-color":e.borderColor});$(".jmb-type-"+e.type).css({color:e.textColor});r.prepend(a);if(e.progressBar){o.addClass("jmb-progress");r.prepend(o)}if(e.stayTime>0){intId=setTimeout(c,e.stayTime);f.maxHtm=parseFloat(e.stayTime);f.hidetm=(new Date).getTime()+f.maxHtm;if(e.progressBar){f.intId=setInterval(l,10)}}$(".jm-title h1").css({color:e.titleColor});$(".jmb-progress").css({"background-color":e.pBarColor});$.SPMsgBox.msg_ctr++;return r},init:function(e){if(e){$.extend($.SPMsgBox.settings,e)}},Show:function(e){var t={};$.extend(t,$.SPMsgBox.settings,e);var n=$.SPMsgBox.JMBContainer(t);if(t.autoHide){setTimeout(function(){$.SPMsgBox.remove(n,t)},t.stayTime)}return n},remove:function(e,t){e.animate({opacity:"0"},600,function(){e.parent().animate({height:"0px"},300,function(){e.parent().remove()})});if(typeof t.close=="function"){t.close()}}}